consul-seed:
  image: "progrium/consul:latest"
  container_name: "consul-seed"
  hostname: "seed"
  ports:
    - "$MACHINE_IP:8300:8300"
    - "$MACHINE_IP:8301:8301"
    - "$MACHINE_IP:8301/udp:8301/udp"
    - "$MACHINE_IP:8302:8302"
    - "$MACHINE_IP:8302/udp:8302/udp"
    - "$MACHINE_IP:8400:8400"
    - "$MACHINE_IP:8500:8500"
    - "$MACHINE_IP:53:53"
    - "$MACHINE_IP:53/udp:53/udp"
  command: "-server -advertise $MACHINE_IP -bootstrap -ui-dir /ui"

consul-client:
  image: "progrium/consul:latest"
  hostname: "client"
  ports:
    - "$MACHINE_IP:8300:8300"
    - "$MACHINE_IP:8301:8301"
    - "$MACHINE_IP:8301/udp:8301/udp"
    - "$MACHINE_IP:8302:8302"
    - "$MACHINE_IP:8302/udp:8302/udp"
    - "$MACHINE_IP:8400:8400"
    - "$MACHINE_IP:8500:8500"
    - "$MACHINE_IP:53:53"
    - "$MACHINE_IP:53/udp:53/udp"
  command: "-advertise $MACHINE_IP -join $SEED_IP"

registrator:
  image: "gliderlabs/registrator:master"
  net: host
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  command: "-ip $MACHINE_IP consul://$MACHINE_IP:8500"

scanner:
  build: "./containers/dnsutils"
  dns:
    - $MACHINE_IP
